### ISSUE TITLE
Bug helicopter

### ISSUE THREAD

**Issue by K-Faktor** [ineedbots/cod4x_bot_warfare#1]
^1******* script runtime error *******
entity is not an array: (file 'maps/mp/bots/_bot.gsc', line 731)
   chopper = level.chopper["allies"];
                   *
^1started from:
(file 'maps/mp/bots/_bot.gsc', line 725)
   wait 0.05;
   *
^1************************************

^1******* script runtime error *******
entity is not an array: (file 'maps/mp/bots/_bot.gsc', line 733)
    chopper = level.chopper["axis"];
                    *
^1started from:
(file 'maps/mp/bots/_bot.gsc', line 725)
   wait 0.05;
   *
^1************************************

^1******* script runtime error *******
undefined is not an object: (file 'maps/mp/bots/_bot.gsc', line 737)
  chopper watchChopper();
          *
^1started from:
(file 'maps/mp/bots/_bot.gsc', line 725)
   wait 0.05;
   *
^1************************************

^1******* script runtime error *******
entity is not an array: (file 'maps/mp/bots/_bot_script.gsc', line 2311)
   chopper = level.chopper[ level.otherTeam[self.team] ];
                   *
^1started from:
(file 'maps/mp/bots/_bot_script.gsc', line 2296)
  wait( RandomIntRange( 2, 4 ) );
  *
^1************************************

^1******* script runtime error *******
entity is not an array: (file 'maps/mp/bots/_bot_script.gsc', line 2311)
   chopper = level.chopper[ level.otherTeam[self.team] ];
                   *
^1started from:
(file 'maps/mp/bots/_bot_script.gsc', line 2296)
  wait( RandomIntRange( 2, 4 ) );
  *
^1************************************

**Comment by ineedbots** [comment]
Thanks for the report, I know of this issue, the isEntity is failing to return the correct value, I need to find a way to test if level.chopper is an entity or an array

**Comment by K-Faktor** [comment]
During testing, I didn't use cod4_new_experience

**Comment by ineedbots** [comment]
I know, the code is trying to account for the level.chopper that cod4 new experience creates, but is false positively accounting for it.

https://github.com/callofduty4x/CoD4x_Server/blob/01b632638ff1ff2925000ef0ffb3653360c60ad6/src/scr_vm_functions.c#L3171

Is returning false for a spawn_helicopter

**Comment by ineedbots** [comment]
isArray returns true for both an [] and a spawnHelicopter, looks like I'll just have to check the cod4 new experience dvar if level.chopper will be an array or a chopper.

**Comment by ineedbots** [comment]
83252684b5b7ab1c6c84381168b92836caf06535 should fix this

**Comment by K-Faktor** [comment]
Works
