### ISSUE TITLE
Cod4x is broken now, unable to play locally with bots

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/cod4x_bot_warfare#11]
The local server thing doesn't work anymore, im not sure if it was an update or something, but the forums are flooded with people having the error "could not find /zone.mod.ff" I don't think this has been fixed and the devs are ignoring people with the issue, so sadly because of this we can't play locally anymore, im not sure if it works for online anymore either as i like to play locally, because of this i have to use the old bot warfare mod for vanilla cod 4.

Here is an image of the error

https://imgur.com/a/8i8hhA1

**Comment by ForeskinJohn** [comment]
did you ever seem to get it working? i have a backed up version but i still have to turn off my internet or it will update
