### ISSUE TITLE
cod4x_bot_warfare 2.01 & WWII mod  Bot Weapon Selection bug

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/cod4x_bot_warfare#12]
All rounds have one or more bot like this one on the[ video](https://www.youtube.com/watch?v=lXtnqNEZKts) .
When he dies and drop the wepon, can see a tinny tinny weapon icon and says [Default weapon](https://et.sytes.net/cod4/bugs/shot0000.jpg).

Another thing,bots get random wepons in random maps, for example RPD all the time, and ak47u, and RPG.
In the bots cfg i put:
set bots_loadout_reasonable "1" is in the bot

And i put in bot_script gsc 

this lines:

ref = id["reference"];

if(reasonable)
{
switch(ref)
{
case "ak47_reflex":                
case "ak47":
case "skorpion":                
case "skorpion_reflex":                
case "uzi":              
case "uzi_reflex":                
case "m21":
case "dragunov":             
case "m4" :                
case "m4_reflex" :
case "m4_silencer" :
case "m14" :                
case "m14_reflex" :              
case "winchester1200" :              
case "winchester1200_reflex" :
case "mp44":                
case "mp44_reflex":                
case "mp5":                
case "mp5_reflex":              
case "g3":                
case "g3_reflex":              
case "m1014":          
case "p90" :              
case "p90_reflex" :                
case "beretta":
case "deserteagle":
case "deserteaglegold":
case "colt45":                              
continue;
}
}

Can we put somehow in the script to blacklist some weapons, to bots? 
If i use this section at default format i get a lot of modern weapons in the game, which is not a good idea couse i want to run WWII. mod with age-appropriate weapons...

**Comment by ineedbots** [comment]
out of scope for this mod, mod is intended to be used with vanilla cod4x
