### ISSUE TITLE
cod4x_bot_warfare 2.01 & WWII mod Server crash couse scripts--- maybeee...?

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/cod4x_bot_warfare#13]
Look [into the logs, telling scripterrors](https://et.sytes.net/cod4/bugs/cod4server-console_crash.log)
[Crashscreen](https://et.sytes.net/cod4/bugs/cod4bot_scripterror.jpg)
Im find another anoying script error, after i completely removed the main_shared folder then redownload/replace From github. [would you look at that](https://et.sytes.net/cod4/bugs/cod4server-console_making_lag.log)... Thats make the game really laggy when spamming those in the server console.

**Comment by ineedbots** [comment]
dupe #12
