### ISSUE TITLE
Chat bot

### ISSUE THREAD

**Issue by K-Faktor** [ineedbots/cod4x_bot_warfare#19]
Hello. I get an error. The chat is turned off for bots

^1******* script runtime error *******
pair 'well that was fun following ' and 'undefined' has unmatching types 'string' and 'undefined': (file 'maps/mp/bots/_bot_chat.gsc', line 1663)
     self BotDoChat( 10, "well that was fun following " + player.name + " for " + time + " seconds" );
                                                        *
^1called from:
(file 'maps/mp/bots/_bot_chat.gsc', line 192)
    self thread bot_chat_follow_watch( a, b, c, d, e, f, g );
                *
^1started from:
(file 'maps/mp/bots/_bot_chat.gsc', line 159)
  self waittill( "bot_event", msg, a, b, c, d, e, f, g );
       *
^1************************************

**Comment by K-Faktor** [comment]
[console.log](https://github.com/ineedbots/cod4x_bot_warfare/files/9387157/console.log)

**Comment by ineedbots** [comment]
bot was following a player that had disconnected,   it chat is disabled,  you could disable the chat by commenting out the chat bootstrap at

**Comment by K-Faktor** [comment]
I did just that. the topic is closed
