### ISSUE TITLE
Balance players independently from bots help

### ISSUE THREAD

**Issue by anddroidd21** [ineedbots/cod4x_bot_warfare#20]
Hi! I am running 3 servers using the BotWarfare mod, and I am having an issue where 6 players are on one team vs 1 player on the enemy team (with bots filling in the rest). Ive tried playing around with bots_team_mode settings but I have yet to figure it out. I dont know how to get the auto balance to distinguish between bots and players.  I also have CoD4 New Experience installed. I figured if there was anyone who could help me it would be you! Any help is appreciated. Would you also know how to increase the tickrate of the server? :D
![fg](https://user-images.githubusercontent.com/114405442/192270511-47b44349-2da1-4f1e-b03a-426d8d964fa0.png)

**Comment by ineedbots** [comment]
instead of "true" or "false"   the dvar needs to be "1" or "0"
