### ISSUE TITLE
issue with mopen warfare?

### ISSUE THREAD

**Issue by Divity** [ineedbots/cod4x_bot_warfare#21]
when adding bots to my server in tandem with open warfare it causes some script error which in turn crash the server immediately, is there anyway to remedy this 

errors::
Going from CS_FREE to CS_CONNECTED for bota num 0
Going from CS_PRIMED to CS_ACTIVE for bota
Going from CS_FREE to CS_CONNECTED for botb num 1
Going from CS_PRIMED to CS_ACTIVE for botb
Going from CS_FREE to CS_CONNECTED for botc num 2
Going from CS_PRIMED to CS_ACTIVE for botc

******* script runtime error *******
undefined is not an array, string, or vector: (file 'openwarfare/_testbots.gsc', line 212)
 primary = game["classWeapons"][self.pers["team"]][ self.pers["classMap"] ][0]; 
               *
called from:
(file 'maps/mp/gametypes/_globallogic.gsc', line 2573)
  self openwarfare\_testbots::menuClass( response );
       *
called from:
(file 'maps/mp/gametypes/_menus.gsc', line 267)
   self [[level.class]](response);
                *
started from:
(file 'maps/mp/gametypes/_menus.gsc', line 101)
  self waittill("menuresponse", menu, response);
       *
************************************
----- Server Shutdown -----

With the reason: Server disconnected
==== ShutdownGame (1) ====
Player bota, 0 dropped: EXE_DISCONNECTED
SV_FreeClientScriptId: 0, 2697 -> 0
Going to CS_FREE for Bot bota
Player botb, 1 dropped: EXE_DISCONNECTED
SV_FreeClientScriptId: 1, 290 -> 0
Going to CS_FREE for Bot botb
Player botc, 2 dropped: EXE_DISCONNECTED
SV_FreeClientScriptId: 2, 179 -> 0
Going to CS_FREE for Bot botc
---------------------------

**Comment by ineedbots** [comment]
Its impossible for me to account for every mod out there, I don't even have access to this mod anyway. You'll have to modify the mod's gsc to fix this. Bot warfare was made with only the vanilla gsc's in mind.
