### ISSUE TITLE
Teams are unbalanced 

### ISSUE THREAD

**Issue by fonix4000** [ineedbots/cod4x_bot_warfare#23]
I use bots when my server is low population (<18 players)  so everytime a player joins, a bot leaves. I make my players always auto assign to avoid team stacking. The problem is that the team balancing when auto assigning does not take into account if a player is a bot or not. I have been trying to struggling to fix this. Here is an example below.

![image](https://user-images.githubusercontent.com/67840268/209350284-3b59867d-88ec-47d3-b1ab-db79ba434477.png)

i was wondering if you had some code to fix this or some help you could provide. Thanks for your great bot mod also.

'Fonix

**Comment by vB1OS** [comment]
I asked a similar question a few months back. Here is the issue link and his response.  https://github.com/ineedbots/cod4x_bot_warfare/issues/20

**Comment by ineedbots** [comment]
Recent release will try to balance teams better, when kicking bots to make room for players, it will prioritize kicking bots on teams with the least amount of players.
