### ISSUE TITLE
Issue with opening menu

### ISSUE THREAD

**Issue by BattleVet** [ineedbots/cod4x_bot_warfare#26]
Hi, I have all of the other bot warfare mods for the other cods installed and can open their menus (I know WaW has the same keys) but I cannot get the menu to open for COD4X when I try to hit the primary and secondary grenade keys. Is there any way to remap them (and if possible, not just for this but for all as there are different keys to open and cycle through the menus)

**Comment by balogune** [comment]
no its not remappable. you have to press g and 4 together if you didnt change ur controls on pc

**Comment by BattleVet** [comment]
> no its not remappable. you have to press g and 4 together if you didnt change ur controls on pc

I've had to use the COD 4 (not COD4X) bot warfare as using the deploy server does not allow you to choose maps and do anything from the in game menus
