### ISSUE TITLE
Bots.txt does not change the names of the bots in game.

### ISSUE THREAD

**Issue by adamclmns** [ineedbots/cod4x_bot_warfare#27]
I may be misunderstanding the intent, as I can find no documentation for this. 

I changed the names in the bots.txt in the Mods/bots folder, but the bots are still bot1, bot2, and so on. 
Is this the intended way to change the bot names in game? I was going to name them all "steve-bot", "dan-bot" and so on after members of my discord group, you know, for the lolz, but it didn't seem to take. Is there a mechanism for changing the bot names? 

If this is not how it works, feel free to close/withdraw the issue. Thank you for your time!

**Comment by ineedbots** [comment]
If fs_game is "" (blank)  then CoD4x will look in the `main` folder for files, and if fs_game is not "" (blank)   it will look in the `mods/<fs_game>` folder for files.
