### ISSUE TITLE
im sorry for making it an issue cant find anywhere else

### ISSUE THREAD

**Issue by tiger710c** [ineedbots/cod4x_bot_warfare#31]
is there of a way of insta leveling up with the server and is there a way to filter the guns the bots use

**Comment by tiger710c** [comment]
and is there a way to enable cheats or at the very least fullbright

**Comment by balogune** [comment]
try this 👍  https://www.youtube.com/watch?v=hSRd7hzW59w

**Comment by tiger710c** [comment]
dude this is perfect ty but will i get like picked up by auto cheat or sum?
