### ISSUE TITLE
Where is the server folder?

### ISSUE THREAD

**Issue by Nightskyy1** [ineedbots/cod4x_bot_warfare#33]
I installed Cod4x the first time today. There seems to be no specific server folder anymore since it's installed directly in the game folder. What am I missing? I couldn't get it to work today, even when putting the files directly into the game folder where the server installation is located. Or did I make a mistake with the server installation? I couldn't find any instructions on it, so I just put the files in the game folder and installed the Cod4x server that way.

**Comment by ineedbots** [comment]
please refer to https://github.com/callofduty4x/CoD4x_Server/wiki/Server-setup

this is not bot warfare related issue
