### ISSUE TITLE
[v2.2.0] Bots with last stand perk have INVISIBLE weapon

### ISSUE THREAD

**Issue by eirisocherry** [ineedbots/cod4x_bot_warfare#34]
v2.2.0:
![image](https://github.com/ineedbots/iw3_bot_warfare/assets/115040224/efbf0861-0fc9-417c-940e-735f5df4ca0a)

In v2.1.0 everything is good:
![image (1)](https://github.com/ineedbots/iw3_bot_warfare/assets/115040224/6e28136e-e73b-4d25-9782-50fdb48a1a12)

I was using Clean COD4X version 21.1 without any other mods.

**Comment by ineedbots** [comment]
You need to be on the latest commit of CoD4x server; as explained here:  https://cod4x.ovh/t/bot-warfare-2-2-0-possible-killstreak-bug/3240/4

**Comment by eirisocherry** [comment]
thank you, I replaced my cod4x18_dedrun.exe with this one and now v2.2.0 bots have weapons
https://drive.google.com/file/d/1_597BFbuNoKX-rP7ZKm-BYTxUKHq8duX/view

https://www.moddb.com/downloads/iw3-bot-warfare-latest
![image (2)](https://github.com/ineedbots/iw3_bot_warfare/assets/115040224/8d4c6f09-4114-4b0c-a7bb-e73dc7ac9781)

**Comment by eirisocherry** [comment]
![image](https://github.com/ineedbots/iw3_bot_warfare/assets/115040224/6018a62d-ef08-4ac5-8bc4-bb3d0d7b512f)
