### ISSUE TITLE
[suggestion] add bot movement recorder

### ISSUE THREAD

**Issue by eirisocherry** [ineedbots/cod4x_bot_warfare#35]
it could be a really useful feature for moviemakers

example:
https://www.youtube.com/watch?v=IqxPKdfu498

it's a server plugin for csgo called bot_mimic: https://forums.alliedmods.net/showthread.php?t=164148

**Comment by ineedbots** [comment]
out of scope for this gsc mod, this would require a c++/c server/client plugin

**Comment by eirisocherry** [comment]
ah okay

**Comment by eirisocherry** [comment]
i didn't completely understand your words but 

if you enjoy coding and know how to make a mod that allows to record bot movement in any cod (mw1 mw2 mw3 bo2 etc), then why not to make it (it doesn't have to be an addition to bot_warfare, can be a whole separate mod)

it could be a really useful feature for moviemakers and maybe for people who wanna fake their gameplay and brag to other people how cool they're are :D

you seem the only one who understand the cod bots, only you can do it

**Comment by ineedbots** [comment]
it would be a separate mod to do this; i am thinking that you would just have to record the baseline state of the client (playerstate) and then record the incoming usercmds, for playback; restore the baseline and playback the usercmds
