### ISSUE TITLE
unable to get this mod working

### ISSUE THREAD

**Issue by OfficialDayL** [ineedbots/cod4x_bot_warfare#38]
No matter what I try this mod doesn't work for me. It is way too complicated to understand how to setup a server and why do I even need to do that? Other mods just work like usual with the usual mod loader function the game haves by default. I just wanna play with bots man, please help...

A video guide with a step by step guide would be good, because as a beginner I see no way to be able to install that...

**Comment by balogune** [comment]
i also had the same issues while trying to install the mod. its a bit of a hassle but its worth it. first download cod4x server and client. 
next copy the contents of the server folder to your cod4 folder.
next download the botwarfare mod
next copy the contents of the botwarfare mod to your cod4 folder.
next run the z_botwarfare_localserver bat file first.
next run the z_botwarfare_playserver and you should be able to run the mod. my name on discord is Soap029 if you need more help.
