### ISSUE TITLE
exceeded maximum number of script variables

### ISSUE THREAD

**Issue by K-Faktor** [ineedbots/cod4x_bot_warfare#4]
Sys_Error: script runtime error
(see console for details)
exceeded maximum number of script variables
[qconsole.log](https://github.com/ineedbots/cod4x_bot_warfare/files/6419157/qconsole.log)

**Comment by ineedbots** [comment]
its possible that the recursive algorithms used (heap and kdtree) maybe too space demanding for gscr script, i'll add a dvar that will disable these data structures at the cost of more cpu time

**Comment by ineedbots** [comment]
and fyi, adding more than 24 bots maybe too much for the gscr vm to handle

**Comment by ineedbots** [comment]
this isn't really a mod specific issue, just a limitation of the game's vm engine

**Comment by ineedbots** [comment]
Found ways to reduce the variable usage, you should be able to have 30 bots in a game now
