### ISSUE TITLE
How to retain your levels etc when starting up this mod?

### ISSUE THREAD

**Issue by MANOUGG** [ineedbots/cod4x_bot_warfare#41]
My levels and unlocks all seem to go when using this. I KNOW there is a command to fix this and retain levels between a normal/dedicated/modded server but I just don't know what that command was. Can anyone please help?

**Comment by ineedbots** [comment]
this isn't bot warfare related, but a client related; make a request to https://github.com/callofduty4x/CoD4x_Client_pub
