### ISSUE TITLE
httpget for a Linux based server and running server without a mod

### ISSUE THREAD

**Issue by vanwayne8** [ineedbots/cod4x_bot_warfare#5]
What does httpget plugin do and is there a version for it for Linux servers? The bot works without it but I hope I'm not missing out something entirely.

My server doesn't have mods so I placed the waypoints and botnames.txt from /mods/bots directly in main so I hope that doesn't break some functionality too as it still works.

**Comment by ineedbots** [comment]
The mod can function normally without, you just won't have network functions like downloading waypoints if the map doesn't have it or checking for the latest version

The plugin is of this source code here https://github.com/ineedbots/cod4x_httpget_plugin

**Comment by ineedbots** [comment]
All http communication is simply grabbing resources from here https://github.com/ineedbots/cod4x_waypoints
